version: 0.0
os: linux 
files:
  - source: /
    destination: home/ec2-user/app
permissions:
  - object: home/ec2-user
    pattern: "app"
    owner: ec2-user
    group: root
    mode: 777
    type:
      - directory
  - object: home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: root
    mode: 777
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install-node-modules.sh
      timeout: 60
      runas: ec2-user
    - location: scripts/build.sh
      timeout: 60
      runas: ec2-user
    - location: scripts/change-permissions.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ec2-user
