export const statusCodes = {
  information: {
    continue: 100,
    switchingProtocol: 201,
    processing: 102,
    earlyHints: 103,
  },
  success: {
    ok: 200,
    created: 201,
    accepted: 202,
    nonAuthoritativeInformation: 203,
    noContent: 204,
    resetContent: 205,
    partialContent: 206,
    multiStatus: 207,
    alreadyReported: 208,
    imUsed: 226,
  },
  redirection: {
    multipleChoice: 300,
    movedPermanently: 301,
    found: 302,
    seeOther: 303,
    notModified: 304,
    useProxy: 305,
    unused: 306,
    temporaryRedirect: 307,
    permanentRedirect: 308,
  },
  clientError: {
    badRequest: 400,
    unauthorized: 401,
    paymentRequired: 402,
    forbidden: 403,
    notFound: 404,
    methodNotAllowed: 405,
    notAcceptable: 406,
    proxyAuthenticationRequired: 407,
    requestTimeout: 408,
    conflict: 409,
    gone: 410,
    lengthRequired: 411,
    preconditionFailed: 412,
    payloadTooLarge: 413,
    uriTooLong: 414,
    unsupportedMediaType: 415,
    rangeNotSatisfiable: 416,
    expectationFailed: 417,
    misdirectedRequest: 421,
    locked: 423,
    failedDependency: 424,
    tooEarly: 425,
    upgradeRequired: 426,
    preconditionRequired: 428,
    tooManyRequests: 429,
    requestHeaderFieldsTooLarge: 431,
    unavailableForLegalReasons: 451,
  },
  server: {
    internalServerError: 500,
    notImplemented: 501,
    badGateway: 502,
    serviceUnavailable: 503,
    gatewayTimeout: 504,
    httpVersionNotSupported: 505,
    variantAlsoNegotiates: 506,
    insufficientStorage: 507,
    loopDetected: 508,
    notExtended: 510,
    networkAuthenticationRequired: 511,
  },
};

export const errorMessages = {
  UNAUTHORIZED: 'Unauthorized',
  UNSUCCESSFUL_LOGIN: 'Unsuccessful Login',
  USERNAME_TAKEN: 'Username already taken',
  MISSING_INFO: 'Missing required information',
  INVALID_USER_ID: 'userId is invalid',
  ERROR_CREATING_USER: 'Error creating user',
  ERROR_FINDING_USER: 'Error finding user',
  ERROR_UPDATING_USER: 'Error updating user',
  ERROR_DELETING_USER: 'Error deleting user',
  ERROR_FINDING_USER_CONVOS: 'Error finding user conversations',
  INVALID_CONVO_ID: 'conversationId is invalid',
  CONVO_DOES_NOT_EXIST: 'Conversation does not exist',
  ERROR_CREATING_CONVO: 'Error creating conversation',
  ERROR_FINDING_CONVO: 'Error finding conversation',
  ERROR_UPDATING_CONVO: 'Error updating conversation',
  ERROR_DELETING_CONVO: 'Error deleting conversation',
  ERROR_FINDING_CONVO_MEMBERS: 'Error finding members in this conversation',
  ERROR_FINDING_MESSAGES: 'Error finding messages',
  ERROR_CREATING_MESSAGE: 'Error creating message',
  USER_ALREADY_IN_CONVO: 'User is already part of this conversation',
  USER_NOT_IN_CONVO: 'User is not a part of this conversation',
  ERROR_ADDING_USER_TO_CONVO: 'Error adding user to conversation',
  ERROR_REMOVING_USER_FROM_CONVO: 'Error removing user from conversation',
};
